[versions]
jdk = "21"
jre = "8"
groovy = "3.0.24"
codenarc = "3.6.0"

[plugins]
gradle-publish = "com.gradle.plugin-publish:1.3.1"
git-publish = "org.ajoberstar.git-publish:5.1.1"
pages = "com.hanggrian.pages:0.2"

[libraries]
# lint
rulebook-codenarc = "com.hanggrian.rulebook:rulebook-codenarc:0.1"
# main
groovy-all = { module = "org.codehaus.groovy:groovy-all", version.ref = "groovy" }
# test
truth = "com.google.truth:truth:1.4.4"
